<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d432b942-eaa4-44e7-a3cd-3f108b03973e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.3.8" />
    <PackageReference Include="FontAwesome" Version="4.7.0" />
  </ItemGroup>

</Project>
